# Generated by Django 3.1.14 on 2023-02-14 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='case_creation_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100)),
                ('Start_date', models.DateTimeField(auto_now_add=True)),
                ('last_modifie_date', models.DateTimeField(auto_now=True)),
                ('case_status', models.CharField(choices=[('RUNING', 'runing'), ('CLOSED', 'closed'), ('ARCHIVIED', 'archieved')], default='runing', max_length=100)),
                ('judges', models.TextField(max_length=100, null=True)),
                ('case_class', models.CharField(max_length=100)),
                ('case_action', models.CharField(max_length=100)),
                ('citation', models.TextField(max_length=100000)),
                ('court_Division', models.CharField(max_length=1000)),
                ('History_docket_number', models.TextField(blank=True, max_length=2000, null=True)),
                ('Histroy_judges', models.TextField(blank=True, max_length=2000, null=True)),
                ('case_outcome', models.TextField(blank=True, max_length=200000000000, null=True)),
                ('Disclaimer', models.TextField(blank=True, max_length=2000000, null=True)),
                ('evidence', models.FileField(upload_to='medai/files/')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='complainant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.TextField(max_length=100, null=True)),
                ('m_name', models.TextField(max_length=100, null=True)),
                ('l_name', models.TextField(max_length=100, null=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.case_creation_model')),
            ],
        ),
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(blank=True, max_length=300, null=True)),
                ('county_code', models.CharField(blank=True, max_length=80, null=True)),
                ('county_abbrevation', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='medai/files/')),
                ('remark', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='defendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.TextField(max_length=100, null=True)),
                ('m_name', models.TextField(max_length=100, null=True)),
                ('l_name', models.TextField(max_length=100, null=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.case_creation_model')),
                ('complainant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.complainant')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='files.counties')),
            ],
        ),
        migrations.AddField(
            model_name='complainant',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='files.counties'),
        ),
    ]
